name: Fetch Env Variables

on: 
  push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print env variable
        run: echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
